import "@radix-ui/themes/styles.css";
import './theme.config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import { Theme, ThemePanel } from '@radix-ui/themes'
import { Toaster } from 'react-hot-toast'
const inter = Inter({
   subsets: ['latin'],
   variable: '--font-inter',
  }) 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance='light' accentColor='blue'>
        <NavBar/>
        <main className='p-5'>{children}</main>
        <ThemePanel />
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#363636',
              color: '#fff',
            },
            success: {
              duration: 3000,
              iconTheme: {
                primary: '#4ade80',
                secondary: '#fff',
              },
            },
            error: {
              duration: 5000,
              iconTheme: {
                primary: '#ef4444',
                secondary: '#fff',
              },
            },
          }}
        />
        </Theme>
        </body>
    </html>
  )
}
